
import { LanguagePack } from './types';

export type Language = 'EN' | 'ES' | 'VI';

export const protocolData: Record<Language, LanguagePack> = {
  EN: {
    headerSubtitle: "Photo Editor & Social AI", mainTitle: "Salon Marketing Suite",
    
    cat5Title: "Photo Branding", cat5Desc: "Stylize photos with AI.",
    cat6Title: "Social Post AI", cat6Desc: "Generate captions for photos.",

    errorApiRateLimit: "API rate limit reached. Please wait a while before trying again.",
    errorApiGeneric: "An error occurred while processing your request. Please try again.",
    passwordError: "Incorrect password", passwordTitle: "Enter Password", passwordPrompt: "Please enter the password to access this tool.", passwordPlaceholder: "Password", passwordSubmit: "Submit",

    brandToolTitle: "AI Photo Branding Tool", brandToolDesc: "Upload a photo, then choose a template to create a new branded image.",
    brandToolUpload: "Drop file to Attach, or browse",
    brandToolOriginal: "Original", brandToolBranded: "Branded Result",
    brandToolChooseTemplate: "Choose a Template", brandToolDownloadBtn: "Download Image",

    brandCategoryClassic: "Classic & Chic",
    brandCategoryVibrant: "Vibrant & Bold",
    brandCategoryLifestyle: "Lifestyle & Cozy",
    brandCategoryHoliday: "Holidays & Events",
    brandCategoryModel: "AI Model",
    brandCategoryPortrait: "Beauty Portrait",
    
    templateStudioTitle: "Elegant Studio", templateStudioDesc: "Clean, high-end studio look.",
    templateSeasonalTitle: "Seasonal Special", templateSeasonalDesc: "Festive, timely, and warm.",
    templateLifestyleTitle: "Lifestyle Glamour", templateLifestyleDesc: "Stylish, real-world context.",
    templateVibrantTitle: "Bold & Vibrant", templateVibrantDesc: "Modern and eye-catching.",
    templateMochaTitle: "Mocha Mood", templateMochaDesc: "Rich, warm, coffee-inspired tones.",
    templateSweaterTitle: "Sweater Weather", templateSweaterDesc: "Cozy textures and soft lighting.",
    templateNeutralsTitle: "Modern Neutrals", templateNeutralsDesc: "Chic, minimalist, and earthy.",
    templateGoldenHourTitle: "Golden Hour Glow", templateGoldenHourDesc: "Warm, sun-kissed outdoor scenes.",
    templateHolidayTitle: "Holiday Cheer", templateHolidayDesc: "Festive designs for any celebration.",

    // Golden Seasons
    templateGoldenSpringTitle: "Spring Bloom Glow",
    templateGoldenSummerTitle: "Summer Sun Glow",
    templateGoldenFallTitle: "Autumn Harvest Glow",
    templateGoldenWinterTitle: "Winter Frost Glow",
    templateGoldenXmasTitle: "Golden Christmas",
    templateGoldenNYTitle: "Golden New Year",
    
    templateModelUrbanTitle: "Urban Model", templateModelUrbanDesc: "Chic outdoor city setting.",
    templateModelLuxuryTitle: "Luxury Living", templateModelLuxuryDesc: "Chic, high-end interior.",
    templateModelSmartTitle: "Smart Seasonal", templateModelSmartDesc: "AI detects season & matches.",
    
    // New Portrait Templates
    templatePortraitGlamTitle: "High Glamour", templatePortraitGlamDesc: "Studio fashion look.",
    templatePortraitSoftTitle: "Soft & Dreamy", templatePortraitSoftDesc: "Ethereal natural light.",
    templatePortraitEdgyTitle: "Edgy & Bold", templatePortraitEdgyDesc: "Dramatic modern vibe.",
    
    holidayChristmas: "Christmas",
    holidayNewYear: "New Year's",
    holidayValentines: "Valentine's",
    holidayHalloween: "Halloween",
    holidayThanksgiving: "Thanksgiving",
    holidayMothersDay: "Mother's Day",

    socialToolTitle: "Social Manager AI", socialToolDesc: "Upload a photo to automatically generate a complete social media strategy.",
    socialToolUpload: "Upload Photo to Analyze",
    socialToolAnalyzeBtn: "Analyze Image",
    socialToolAnalyzing: "Scanning...",
    socialToolAnalysisTitle: "AI Analysis",
    socialToolGenerateBtn: "Generate Strategy",
    socialToolGenerating: "Creating Content...",
    socialTabInsta: "Instagram",
    socialTabFB: "Facebook",
    socialTabTikTok: "TikTok Script",
    socialSectionHooks: "Viral Hooks",
    socialSectionComments: "Engagement Boosters",
    socialSectionHashtags: "Smart Hashtags",
    socialSectionScore: "Virality Score",
    socialToolQ1: "Notes (Optional)",
    socialToolQ2: "",
    socialToolQ3: "",
    socialToolResultTitle: "",
    socialToolCopyBtn: "Copy",
    
    socialToolToneLabel: "Vibe",
    socialToolToneProfessional: "Professional",
    socialToolToneFriendly: "Friendly",
    socialToolTonePlayful: "Playful",
    socialToolToneEmpathetic: "Empathetic",
    socialToolToneUrgent: "Urgent",
    socialToolToneInformative: "Informative",
    
    socialToolLengthLabel: "Length",
    socialToolLengthShort: "Short",
    socialToolLengthMedium: "Medium",
    socialToolLengthDetailed: "Long",
    
    socialToolPlatformLabel: "Platform",
    socialToolPlatformInstagram: "Instagram",
    socialToolPlatformFacebook: "Facebook",
    socialToolPlatformGoogle: "Google Business",

    // Promo Tool
    promoToolTitle: "Promotion Generator", promoToolDesc: "Create professional graphics and captions for your promotions.",
    promoToolTitleLabel: "Promotion Title",
    promoToolOfferLabel: "Main Offer",
    promoToolOffer2Label: "Secondary Offer (Optional)",
    promoToolNotesLabel: "Notes / Restrictions",
    promoToolDatesLabel: "Valid Dates",
    promoToolKeywordsLabel: "Keywords",
    promoToolStyleLabel: "Graphic Style",
    promoToolGenerateBtn: "Generate Graphic",
    promoToolResultTitle: "Generated Promotion",
    promoToolDownloadBtn: "Download Graphic",
    promoStyleElegant: "Elegant",
    promoStyleModern: "Modern Luxury",
    promoStyleSeasonal: "Seasonal",
    promoStylePlayful: "Playful",
    promoStyleLifestyle: "Lifestyle",
    promoStyleNatural: "Natural",
    promoStyleSplit: "Split Screen",

    // Idea Tool
    ideaToolTitle: "Promotion Idea AI", ideaToolDesc: "Brainstorm new promotion strategies tailored to your salon.",
    ideaToolInstantTitle: "Instant Ideas", ideaToolInstantDesc: "Get 3 quick, high-impact ideas instantly.",
    ideaToolDeepDiveTitle: "Deep Dive Strategy", ideaToolDeepDiveDesc: "Answer a few questions for a tailored strategy.",
    ideaToolChatbotTitle: "Chat with AI Coach", ideaToolChatbotDesc: "Discuss and refine ideas interactively.",
    ideaToolBack: "Back", ideaToolNext: "Next", ideaToolSubmit: "Submit",
    ideaToolResultTitle: "Suggested Promotions",
    ideaToolAddToPromoBtn: "Create Graphic",
    ideaToolCreateLandingPageBtn: "Create Landing Page",
    ideaToolCreateGraphicBtn: "Create Graphic",
    ideaToolRestart: "Start Over",
    chatbotWelcomeMessage: "Hello! I'm your salon marketing assistant. How can I help you brainstorm a promotion today?",
    chatbotInputPlaceholder: "Type your message...",
    q1Title: "Business Goal", q1Prompt: "What is your main goal?", q1o1: "Increase New Clients", q1o2: "Retain Existing Clients", q1o3: "Boost Revenue per Visit", q1o4: "Fill Slow Days", q1o5: "Promote New Service",
    q2Title: "Target Audience", q2Prompt: "Who are we targeting?", q2o1: "Young Professionals", q2o2: "Students", q2o3: "Moms / Busy Women", q2o4: "Luxury Seekers",
    q3Title: "Service Focus", q3Prompt: "Which service to highlight?", q3o1: "General / All", q3o2: "Premium Pedicures", q3o3: "Combo Packages", q3o4: "Nail Art / Trends",
    q3subPremium: "Which Pedicure?", q3sp1: "Ocean Breeze", q3sp2: "Matcha", q3sp3: "Rose", q3sp4: "Collagen", q3sp5: "Herbal Detox",
    q3subCombo: "Which Combo?", q3sc1: "Mani + Pedi", q3sc2: "Gel Mani + Pedi", q3sc3: "Dip + Pedi", q3sc4: "Gel X + Pedi", q3sc5: "Full Set + Pedi", q3sc6: "Mommy & Me",
    q4Title: "Vibe", q4Prompt: "Desired customer experience?", q4o1: "Relaxing / Spa", q4o2: "Quick / Efficient", q4o3: "Fun / Social", q4o4: "Luxury / Treat",
    q5Title: "Financials", q5Prompt: "Financial goal?", q5o1: "Volume (More tickets)", q5o2: "Value (Higher tickets)", q5o3: "Cash Flow", q5o4: "Long-term Value",
    q6Title: "Brand", q6Prompt: "Brand connection?", q6o1: "Quality", q6o2: "Value", q6o3: "Cleanliness", q6o4: "Artistry", q6o5: "Customer Service",
    q7Title: "Edge", q7Prompt: "Competitive Advantage", q7Other: "Describe your edge...",
    q8Title: "Restrictions", q8Prompt: "Any constraints?", q8o1: "None", q8o2: "Weekdays Only", q8o3: "Specific Techs", q8o4: "New Clients Only",

    // Video Tool
    videoToolTitle: "AI Video Creator", videoToolDesc: "Animate your photos into engaging social media videos.",
    videoToolStyleLabel: "Motion Style",
    videoToolFormatLabel: "Format",
    videoToolGenerateBtn: "Generate Video",
    videoToolResultTitle: "Generated Video",
    videoToolDownloadBtn: "Download Video",
    motionStyleZoom: "Slow Zoom",
    motionStylePan: "Pan",
    motionStyleSparkle: "Sparkle",
    motionStylePetals: "Floating Petals",
    videoToolFormatRegular: "16:9 (Landscape)",
    videoToolFormatSquare: "1:1 (Square)",
    videoToolFormatReel: "9:16 (Reel/TikTok)",

    // Brochure Tool
    brochureToolTitle: "Brochure Creator", brochureToolDesc: "Design professional service brochures.",
    brochureToolHeadlineLabel: "Headline",
    brochureToolSubheadlineLabel: "Sub-headline",
    brochureToolPriceLabel: "Price",
    brochureToolBlock1HeadlineLabel: "Block 1 Title",
    brochureToolBlock1FeatureLabel: "Feature",
    brochureToolBlock2HeadlineLabel: "Block 2 Title",
    brochureToolBlock2FeatureLabel: "Feature",
    brochureToolCallToActionLabel: "Call to Action",
    brochureToolFooterLabel: "Footer Text",
    brochureToolStyleLabel: "Design Style",
    brochureToolGenerateBtn: "Generate Design",
    brochureToolResultTitle: "Brochure Preview",
    brochureToolDownloadBtn: "Download Brochure",
    brochureStyleLuxury: "Luxury",
    brochureStyleTrendy: "Trendy",
    brochureStyleElegant: "Elegant",
    brochureStyleNatural: "Natural",
    brochureStyleBold: "Bold",
    brochureStyleModern: "Modern",
    brochureStyleMinimal: "Minimal",
    brochureStyleProfessional: "Professional",

    // Landing Page Tool
    landingPageToolTitle: "Landing Page Creator",
    landingPageToolDesc: "Generate a high-converting HTML landing page.",
    landingPageSelectedPromos: "Selected Promotions",
    landingPageToneLabel: "Tone",
    landingPageLayoutLabel: "Layout",
    landingPageGenerateBtn: "Generate Page",
    landingPageToneProfessional: "Professional",
    landingPageToneExciting: "Exciting",
    landingPageToneBenefit: "Benefit-Driven",
    landingPageLayoutSingle: "Single Column",
    landingPageLayoutImageLeft: "Image Left",
    landingPageLayoutImageRight: "Image Right",

    // Coach Tool
    coachTitle: "AI Business Coach", coachDesc: "Real-time voice consultation for your salon business.",
    coachStatusIdle: "Ready", coachStatusConnecting: "Connecting...",
    coachStatusListening: "Listening...", coachStatusSpeaking: "Speaking...", coachStatusError: "Error",
    coachMicPermissionError: "Microphone permission denied",
    
    content: {}
  },
  ES: {
    headerSubtitle: "Editor de Fotos y Redes Sociales", mainTitle: "Suite de Marketing",
    cat5Title: "Marca de Fotos", cat5Desc: "Estiliza fotos con IA.",
    cat6Title: "IA para Redes Sociales", cat6Desc: "Genera descripciones para fotos.",
    errorApiRateLimit: "Se ha alcanzado el límite de la API. Por favor, espere un momento antes de volver a intentarlo.",
    errorApiGeneric: "Ocurrió un error al procesar su solicitud. Por favor, intente de nuevo.",
    passwordError: "Contraseña incorrecta", passwordTitle: "Introducir Contraseña", passwordPrompt: "Por favor ingrese la contraseña.", passwordPlaceholder: "Contraseña", passwordSubmit: "Enviar",
    brandToolTitle: "Herramienta de Marca de Fotos con IA", brandToolDesc: "Sube una foto y elige una plantilla.",
    brandToolUpload: "Arrastra un archivo para Adjuntar, o explora",
    brandToolOriginal: "Original", brandToolBranded: "Con Marca",
    brandToolChooseTemplate: "Elige una Plantilla", brandToolDownloadBtn: "Descargar Imagen",
    brandCategoryClassic: "Classic & Chic",
    brandCategoryVibrant: "Vibrant & Bold",
    brandCategoryLifestyle: "Lifestyle & Cozy",
    brandCategoryHoliday: "Holidays & Events",
    brandCategoryModel: "AI Model",
    brandCategoryPortrait: "Beauty Portrait",
    templateStudioTitle: "Estudio Elegante", templateStudioDesc: "Aspecto limpio y de alta gama.",
    templateSeasonalTitle: "Especial de Temporada", templateSeasonalDesc: "Festivo, oportuno y cálido.",
    templateLifestyleTitle: "Glamour de Estilo de Vida", templateLifestyleDesc: "Contexto elegante y real.",
    templateVibrantTitle: "Atrevido y Vibrante", templateVibrantDesc: "Moderno y llamativo.",
    templateMochaTitle: "Ambiente Moca", templateMochaDesc: "Tonos ricos, cálidos, inspirados en el café.",
    templateSweaterTitle: "Clima de Suéter", templateSweaterDesc: "Texturas acogedoras y luz suave.",
    templateNeutralsTitle: "Neutros Modernos", templateNeutralsDesc: "Chic, minimalista y terroso.",
    templateGoldenHourTitle: "Brillo Dorado", templateGoldenHourDesc: "Escenas cálidas y soleadas al aire libre.",
    templateHolidayTitle: "Alegría Festiva", templateHolidayDesc: "Diseños festivos para cualquier celebración.",

    templateGoldenSpringTitle: "Spring Bloom Glow",
    templateGoldenSummerTitle: "Summer Sun Glow",
    templateGoldenFallTitle: "Autumn Harvest Glow",
    templateGoldenWinterTitle: "Winter Frost Glow",
    templateGoldenXmasTitle: "Golden Christmas",
    templateGoldenNYTitle: "Golden New Year",

    templateModelUrbanTitle: "Urban Model", templateModelUrbanDesc: "Outdoor city.",
    templateModelLuxuryTitle: "Luxury Living", templateModelLuxuryDesc: "Chic, high-end interior.",
    templateModelSmartTitle: "Smart Seasonal", templateModelSmartDesc: "AI detects season & matches.",
    templatePortraitGlamTitle: "High Glamour", templatePortraitGlamDesc: "Studio fashion.",
    templatePortraitSoftTitle: "Soft & Dreamy", templatePortraitSoftDesc: "Ethereal.",
    templatePortraitEdgyTitle: "Edgy & Bold", templatePortraitEdgyDesc: "Dramatic.",
    holidayChristmas: "Navidad", holidayNewYear: "Año Nuevo", holidayValentines: "San Valentín", holidayHalloween: "Halloween", holidayThanksgiving: "Acción de Gracias", holidayMothersDay: "Día de la Madre",
    socialToolTitle: "Social Manager AI", socialToolDesc: "Generate content.", socialToolUpload: "Upload", socialToolAnalyzeBtn: "Analyze", socialToolAnalyzing: "Scanning", socialToolAnalysisTitle: "Analysis", socialToolGenerateBtn: "Generate", socialToolGenerating: "Generating", socialTabInsta: "IG", socialTabFB: "FB", socialTabTikTok: "TikTok", socialSectionHooks: "Hooks", socialSectionComments: "Comentarios de Participación", socialSectionHashtags: "Tags", socialSectionScore: "Score", socialToolQ1: "Notes", socialToolQ2: "", socialToolQ3: "", socialToolResultTitle: "", socialToolCopyBtn: "Copy",
    socialToolToneLabel: "Tono", socialToolToneProfessional: "Profesional", socialToolToneFriendly: "Amistoso", socialToolTonePlayful: "Juguetón", socialToolToneEmpathetic: "Empático", socialToolToneUrgent: "Urgente", socialToolToneInformative: "Informativo",
    socialToolLengthLabel: "Longitud", socialToolLengthShort: "Corto", socialToolLengthMedium: "Mediano", socialToolLengthDetailed: "Detallado",
    socialToolPlatformLabel: "Plataforma", socialToolPlatformInstagram: "Instagram", socialToolPlatformFacebook: "Facebook", socialToolPlatformGoogle: "Google Business",
    promoToolTitle: "Promotion Generator", promoToolDesc: "Create professional graphics and captions.",
    promoToolTitleLabel: "Title", promoToolOfferLabel: "Offer", promoToolOffer2Label: "Secondary Offer", promoToolNotesLabel: "Notes", promoToolDatesLabel: "Dates", promoToolKeywordsLabel: "Keywords", promoToolStyleLabel: "Style",
    promoToolGenerateBtn: "Generate", promoToolResultTitle: "Result", promoToolDownloadBtn: "Download",
    promoStyleElegant: "Elegant", promoStyleModern: "Modern", promoStyleSeasonal: "Seasonal", promoStylePlayful: "Playful", promoStyleLifestyle: "Lifestyle", promoStyleNatural: "Natural", promoStyleSplit: "Split",
    ideaToolTitle: "Promotion Idea AI", ideaToolDesc: "Brainstorm ideas.",
    ideaToolInstantTitle: "Instant Ideas", ideaToolInstantDesc: "Quick ideas.", ideaToolDeepDiveTitle: "Deep Dive", ideaToolDeepDiveDesc: "Tailored strategy.", ideaToolChatbotTitle: "Chat Coach", ideaToolChatbotDesc: "Interactive chat.",
    ideaToolBack: "Back", ideaToolNext: "Next", ideaToolSubmit: "Submit", ideaToolResultTitle: "Results", ideaToolAddToPromoBtn: "Create Graphic", ideaToolCreateLandingPageBtn: "Create Page", ideaToolCreateGraphicBtn: "Create Graphic", ideaToolRestart: "Restart",
    chatbotWelcomeMessage: "Hola! How can I help?", chatbotInputPlaceholder: "Type here...",
    q1Title: "Goal", q1Prompt: "Goal?", q1o1: "New Clients", q1o2: "Retention", q1o3: "Revenue", q1o4: "Slow Days", q1o5: "New Service",
    q2Title: "Audience", q2Prompt: "Target?", q2o1: "Pros", q2o2: "Students", q2o3: "Moms", q2o4: "Luxury",
    q3Title: "Service", q3Prompt: "Service?", q3o1: "All", q3o2: "Premium Pedi", q3o3: "Combos", q3o4: "Nail Art",
    q3subPremium: "Which Pedi?", q3sp1: "Ocean", q3sp2: "Matcha", q3sp3: "Rose", q3sp4: "Collagen", q3sp5: "Herbal",
    q3subCombo: "Which Combo?", q3sc1: "Mani+Pedi", q3sc2: "Gel+Pedi", q3sc3: "Dip+Pedi", q3sc4: "GelX+Pedi", q3sc5: "Full+Pedi", q3sc6: "Mommy+Me",
    q4Title: "Vibe", q4Prompt: "Vibe?", q4o1: "Relaxing", q4o2: "Quick", q4o3: "Fun", q4o4: "Luxury",
    q5Title: "Finance", q5Prompt: "Goal?", q5o1: "Volume", q5o2: "Value", q5o3: "Cash", q5o4: "LTV",
    q6Title: "Brand", q6Prompt: "Brand?", q6o1: "Quality", q6o2: "Value", q6o3: "Clean", q6o4: "Art", q6o5: "Service",
    q7Title: "Edge", q7Prompt: "Edge?", q7Other: "Describe...",
    q8Title: "Restrictions", q8Prompt: "Limits?", q8o1: "None", q8o2: "Weekdays", q8o3: "Techs", q8o4: "New Only",
    videoToolTitle: "AI Video", videoToolDesc: "Create videos.", videoToolStyleLabel: "Style", videoToolFormatLabel: "Format", videoToolGenerateBtn: "Generate", videoToolResultTitle: "Result", videoToolDownloadBtn: "Download",
    motionStyleZoom: "Zoom", motionStylePan: "Pan", motionStyleSparkle: "Sparkle", motionStylePetals: "Petals", videoToolFormatRegular: "16:9", videoToolFormatSquare: "1:1", videoToolFormatReel: "9:16",
    brochureToolTitle: "Brochure Creator", brochureToolDesc: "Design brochures.", brochureToolHeadlineLabel: "Headline", brochureToolSubheadlineLabel: "Sub-head", brochureToolPriceLabel: "Price", brochureToolBlock1HeadlineLabel: "Block 1", brochureToolBlock1FeatureLabel: "Feature", brochureToolBlock2HeadlineLabel: "Block 2", brochureToolBlock2FeatureLabel: "Feature", brochureToolCallToActionLabel: "CTA", brochureToolFooterLabel: "Footer", brochureToolStyleLabel: "Style", brochureToolGenerateBtn: "Generate", brochureToolResultTitle: "Preview", brochureToolDownloadBtn: "Download",
    brochureStyleLuxury: "Luxury", brochureStyleTrendy: "Trendy", brochureStyleElegant: "Elegant", brochureStyleNatural: "Natural", brochureStyleBold: "Bold", brochureStyleModern: "Modern", brochureStyleMinimal: "Minimal", brochureStyleProfessional: "Professional",
    landingPageToolTitle: "Landing Page", landingPageToolDesc: "Create HTML.", landingPageSelectedPromos: "Promos", landingPageToneLabel: "Tone", landingPageLayoutLabel: "Layout", landingPageGenerateBtn: "Generate", landingPageToneProfessional: "Professional", landingPageToneExciting: "Exciting", landingPageToneBenefit: "Benefit", landingPageLayoutSingle: "Single", landingPageLayoutImageLeft: "Left", landingPageLayoutImageRight: "Right",
    coachTitle: "Business Coach", coachDesc: "Voice chat.", coachStatusIdle: "Ready", coachStatusConnecting: "Connecting", coachStatusListening: "Listening", coachStatusSpeaking: "Speaking", coachStatusError: "Error", coachMicPermissionError: "Mic Error",
    content: {}
  },
  VI: {
    headerSubtitle: "Trình chỉnh sửa ảnh & MXH", mainTitle: "Bộ công cụ Tiếp thị",
    cat5Title: "Xây dựng thương hiệu ảnh", cat5Desc: "Thêm thương hiệu salon vào ảnh bằng AI.",
    cat6Title: "AI Viết bài Mạng xã hội", cat6Desc: "Tạo chú thích cho ảnh.",
    errorApiRateLimit: "Đã đạt đến giới hạn API. Vui lòng đợi một lát trước khi thử lại.",
    errorApiGeneric: "Đã xảy ra lỗi khi xử lý yêu cầu của bạn. Vui lòng thử lại.",
    passwordError: "Mật khẩu không đúng", passwordTitle: "Nhập mật khẩu", passwordPrompt: "Vui lòng nhập mật khẩu.", passwordPlaceholder: "Mật khẩu", passwordSubmit: "Gửi",
    brandToolTitle: "Công cụ xây dựng thương hiệu ảnh bằng AI", brandToolDesc: "Tải ảnh lên và chọn mẫu.",
    brandToolUpload: "Thả tệp để đính kèm hoặc duyệt",
    brandToolOriginal: "Bản gốc", brandToolBranded: "Kết quả có thương hiệu",
    brandToolChooseTemplate: "Chọn một Mẫu", brandToolDownloadBtn: "Tải hình ảnh",
    brandCategoryClassic: "Classic & Chic",
    brandCategoryVibrant: "Vibrant & Bold",
    brandCategoryLifestyle: "Lifestyle & Cozy",
    brandCategoryHoliday: "Holidays & Events",
    brandCategoryModel: "AI Model",
    brandCategoryPortrait: "Beauty Portrait",
    templateStudioTitle: "Studio Thanh lịch", templateStudioDesc: "Vẻ ngoài sạch sẽ, cao cấp.",
    templateSeasonalTitle: "Ưu đãi Theo mùa", templateSeasonalDesc: "Không khí lễ hội, hợp thời.",
    templateLifestyleTitle: "Phong cách Sống Sang trọng", templateLifestyleDesc: "Bối cảnh đời thực, sành điệu.",
    templateVibrantTitle: "Táo bạo & Sôi động", templateVibrantDesc: "Hiện đại và bắt mắt.",
    templateMochaTitle: "Tâm trạng Mocha", templateMochaDesc: "Tông màu đậm, ấm áp.",
    templateSweaterTitle: "Thời tiết Áo len", templateSweaterDesc: "Chất liệu ấm cúng.",
    templateNeutralsTitle: "Gam màu Trung tính", templateNeutralsDesc: "Sang trọng, tối giản.",
    templateGoldenHourTitle: "Ánh sáng Giờ vàng", templateGoldenHourDesc: "Khung cảnh ngoài trời ấm áp.",
    templateHolidayTitle: "Không khí Lễ hội", templateHolidayDesc: "Thiết kế lễ hội.",

    templateGoldenSpringTitle: "Spring Bloom Glow",
    templateGoldenSummerTitle: "Summer Sun Glow",
    templateGoldenFallTitle: "Autumn Harvest Glow",
    templateGoldenWinterTitle: "Winter Frost Glow",
    templateGoldenXmasTitle: "Golden Christmas",
    templateGoldenNYTitle: "Golden New Year",

    templateModelUrbanTitle: "Urban Model", templateModelUrbanDesc: "Outdoor city.",
    templateModelLuxuryTitle: "Luxury Living", templateModelLuxuryDesc: "Chic, high-end interior.",
    templateModelSmartTitle: "Smart Seasonal", templateModelSmartDesc: "AI detects season & matches.",
    templatePortraitGlamTitle: "High Glamour", templatePortraitGlamDesc: "Studio fashion.",
    templatePortraitSoftTitle: "Soft & Dreamy", templatePortraitSoftDesc: "Ethereal.",
    templatePortraitEdgyTitle: "Edgy & Bold", templatePortraitEdgyDesc: "Dramatic.",
    holidayChristmas: "Giáng sinh", holidayNewYear: "Năm mới", holidayValentines: "Lễ tình nhân", holidayHalloween: "Halloween", holidayThanksgiving: "Lễ Tạ ơn", holidayMothersDay: "Ngày của Mẹ",
    socialToolTitle: "Social Manager AI", socialToolDesc: "Generate content.", socialToolUpload: "Upload", socialToolAnalyzeBtn: "Analyze", socialToolAnalyzing: "Scanning", socialToolAnalysisTitle: "Analysis", socialToolGenerateBtn: "Generate", socialToolGenerating: "Generating", socialTabInsta: "IG", socialTabFB: "FB", socialTabTikTok: "TikTok", socialSectionHooks: "Hooks", socialSectionComments: "Bình luận Tương tác", socialSectionHashtags: "Tags", socialSectionScore: "Score", socialToolQ1: "Notes", socialToolQ2: "", socialToolQ3: "", socialToolResultTitle: "", socialToolCopyBtn: "Copy",
    socialToolToneLabel: "Tông giọng", socialToolToneProfessional: "Chuyên nghiệp", socialToolToneFriendly: "Thân thiện", socialToolTonePlayful: "Vui tươi", socialToolToneEmpathetic: "Đồng cảm", socialToolToneUrgent: "Khẩn cấp", socialToolToneInformative: "Thông tin",
    socialToolLengthLabel: "Độ dài", socialToolLengthShort: "Ngắn", socialToolLengthMedium: "Trung", socialToolLengthDetailed: "Dài",
    socialToolPlatformLabel: "Nền tảng", socialToolPlatformInstagram: "Instagram", socialToolPlatformFacebook: "Facebook", socialToolPlatformGoogle: "Google",
    promoToolTitle: "Promotion Generator", promoToolDesc: "Create graphics.", promoToolTitleLabel: "Title", promoToolOfferLabel: "Offer", promoToolOffer2Label: "Secondary Offer", promoToolNotesLabel: "Notes", promoToolDatesLabel: "Dates", promoToolKeywordsLabel: "Keywords", promoToolStyleLabel: "Style", promoToolGenerateBtn: "Generate", promoToolResultTitle: "Result", promoToolDownloadBtn: "Download",
    promoStyleElegant: "Elegant", promoStyleModern: "Modern", promoStyleSeasonal: "Seasonal", promoStylePlayful: "Playful", promoStyleLifestyle: "Lifestyle", promoStyleNatural: "Natural", promoStyleSplit: "Split",
    ideaToolTitle: "Promotion Idea AI", ideaToolDesc: "Brainstorm.",
    ideaToolInstantTitle: "Instant Ideas", ideaToolInstantDesc: "Quick ideas.", ideaToolDeepDiveTitle: "Deep Dive", ideaToolDeepDiveDesc: "Tailored.", ideaToolChatbotTitle: "Chat Coach", ideaToolChatbotDesc: "Chat.",
    ideaToolBack: "Back", ideaToolNext: "Next", ideaToolSubmit: "Submit", ideaToolResultTitle: "Results", ideaToolAddToPromoBtn: "Create Graphic", ideaToolCreateLandingPageBtn: "Create Page", ideaToolCreateGraphicBtn: "Create Graphic", ideaToolRestart: "Restart",
    chatbotWelcomeMessage: "Hello! How can I help?", chatbotInputPlaceholder: "Type here...",
    q1Title: "Goal", q1Prompt: "Goal?", q1o1: "New Clients", q1o2: "Retention", q1o3: "Revenue", q1o4: "Slow Days", q1o5: "New Service",
    q2Title: "Audience", q2Prompt: "Target?", q2o1: "Pros", q2o2: "Students", q2o3: "Moms", q2o4: "Luxury",
    q3Title: "Service", q3Prompt: "Service?", q3o1: "All", q3o2: "Premium Pedi", q3o3: "Combos", q3o4: "Nail Art",
    q3subPremium: "Which Pedi?", q3sp1: "Ocean", q3sp2: "Matcha", q3sp3: "Rose", q3sp4: "Collagen", q3sp5: "Herbal",
    q3subCombo: "Which Combo?", q3sc1: "Mani+Pedi", q3sc2: "Gel+Pedi", q3sc3: "Dip+Pedi", q3sc4: "GelX+Pedi", q3sc5: "Full+Pedi", q3sc6: "Mommy+Me",
    q4Title: "Vibe", q4Prompt: "Vibe?", q4o1: "Relaxing", q4o2: "Quick", q4o3: "Fun", q4o4: "Luxury",
    q5Title: "Finance", q5Prompt: "Goal?", q5o1: "Volume", q5o2: "Value", q5o3: "Cash", q5o4: "LTV",
    q6Title: "Brand", q6Prompt: "Brand?", q6o1: "Quality", q6o2: "Value", q6o3: "Clean", q6o4: "Art", q6o5: "Service",
    q7Title: "Edge", q7Prompt: "Edge?", q7Other: "Describe...",
    q8Title: "Restrictions", q8Prompt: "Limits?", q8o1: "None", q8o2: "Weekdays", q8o3: "Techs", q8o4: "New Only",
    videoToolTitle: "AI Video", videoToolDesc: "Create videos.", videoToolStyleLabel: "Style", videoToolFormatLabel: "Format", videoToolGenerateBtn: "Generate", videoToolResultTitle: "Result", videoToolDownloadBtn: "Download",
    motionStyleZoom: "Zoom", motionStylePan: "Pan", motionStyleSparkle: "Sparkle", motionStylePetals: "Petals", videoToolFormatRegular: "16:9", videoToolFormatSquare: "1:1", videoToolFormatReel: "9:16",
    brochureToolTitle: "Brochure Creator", brochureToolDesc: "Design brochures.", brochureToolHeadlineLabel: "Headline", brochureToolSubheadlineLabel: "Sub-head", brochureToolPriceLabel: "Price", brochureToolBlock1HeadlineLabel: "Block 1", brochureToolBlock1FeatureLabel: "Feature", brochureToolBlock2HeadlineLabel: "Block 2", brochureToolBlock2FeatureLabel: "Feature", brochureToolCallToActionLabel: "CTA", brochureToolFooterLabel: "Footer", brochureToolStyleLabel: "Style", brochureToolGenerateBtn: "Generate", brochureToolResultTitle: "Preview", brochureToolDownloadBtn: "Download",
    brochureStyleLuxury: "Luxury", brochureStyleTrendy: "Trendy", brochureStyleElegant: "Elegant", brochureStyleNatural: "Natural", brochureStyleBold: "Bold", brochureStyleModern: "Modern", brochureStyleMinimal: "Minimal", brochureStyleProfessional: "Professional",
    landingPageToolTitle: "Landing Page", landingPageToolDesc: "Create HTML.", landingPageSelectedPromos: "Promos", landingPageToneLabel: "Tone", landingPageLayoutLabel: "Layout", landingPageGenerateBtn: "Generate", landingPageToneProfessional: "Professional", landingPageToneExciting: "Exciting", landingPageToneBenefit: "Benefit", landingPageLayoutSingle: "Single", landingPageLayoutImageLeft: "Left", landingPageLayoutImageRight: "Right",
    coachTitle: "Business Coach", coachDesc: "Voice chat.", coachStatusIdle: "Ready", coachStatusConnecting: "Connecting", coachStatusListening: "Listening", coachStatusSpeaking: "Speaking", coachStatusError: "Error", coachMicPermissionError: "Mic Error",
    content: {}
  }
};
